# Generated by Django 2.2.17 on 2020-12-19 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('speciality', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('contact_no', models.IntegerField()),
                ('ot', models.IntegerField()),
                ('beds', models.IntegerField()),
                ('bgAp', models.IntegerField()),
                ('bgBp', models.IntegerField()),
                ('bgABp', models.IntegerField()),
                ('bgOp', models.IntegerField()),
                ('bgAn', models.IntegerField()),
                ('bgBn', models.IntegerField()),
                ('bgABn', models.IntegerField()),
                ('bgOn', models.IntegerField()),
                ('timing', models.CharField(max_length=50)),
            ],
        ),
    ]
