# Generated by Django 2.2.17 on 2020-12-19 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='speciality',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
