# Generated by Django 2.2.17 on 2020-12-20 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201219_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='show',
            field=models.BooleanField(default=False),
        ),
    ]
